#!/usr/bin/env bash
# generate.sh - Generate minimal GDExtension autowrapper stubs
#
# This generates the bare-minimum autowrapper code needed to compile
# the OpenCASCADE.gd extension. It produces a module.h with empty
# registration/unregistration stubs.
#
# Future versions will generate actual OpenCASCADE bindings.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AUTOWRAPPER_DIR="$PROJECT_ROOT/src/autowrapper"

mkdir -p "$AUTOWRAPPER_DIR"

# Generate module.h with empty stubs
cat > "$AUTOWRAPPER_DIR/module.h" << 'HEADER_EOF'
// AUTOGENERATED by OpenCASCADE.gd-autowrapper/generate.sh - DO NOT EDIT
#ifndef AUTOWRAPPER_MODULE_H
#define AUTOWRAPPER_MODULE_H

#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/godot.hpp>

inline void gdext_initialize_module_auto(godot::ModuleInitializationLevel p_level) {
    (void)p_level;
}

inline void gdext_uninitialize_module_auto(godot::ModuleInitializationLevel p_level) {
    (void)p_level;
}

#endif // AUTOWRAPPER_MODULE_H
HEADER_EOF

echo "OpenCASCADE.gd-autowrapper: generated stubs in $AUTOWRAPPER_DIR"
