"""Generate module.h — the master registration header that includes all wrappers."""

from __future__ import annotations

from pathlib import Path

from model import ModuleDecl


def generate_module_header(modules: list[ModuleDecl], output_dir: Path) -> str:
    """Generate module.h with all includes and registration calls."""
    output_dir.mkdir(parents=True, exist_ok=True)
    file_path = output_dir / "module.h"

    includes = []
    registrations = []

    for mod in modules:
        for cls in mod.classes:
            includes.append(f'#include "{cls.wrapper_name}.hpp"')
            registrations.append(f'    godot::ClassDB::register_class<{cls.wrapper_name}>();')

    content = f"""// AUTOGENERATED by OpenCASCADE.gd-autowrapper — DO NOT EDIT
#ifndef AUTOWRAPPER_MODULE_H
#define AUTOWRAPPER_MODULE_H

#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/godot.hpp>

{chr(10).join(includes)}

inline void gdext_initialize_module_auto(godot::ModuleInitializationLevel p_level) {{
    if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {{
        return;
    }}
{chr(10).join(registrations)}
}}

inline void gdext_uninitialize_module_auto(godot::ModuleInitializationLevel p_level) {{
    (void)p_level;
}}

#endif // AUTOWRAPPER_MODULE_H
"""

    file_path.write_text(content)
    return str(file_path)
