"""Generate module.h — the master registration header that includes all wrappers."""

from __future__ import annotations

from pathlib import Path

from model import ModuleDecl

# Primitive out-param wrapper classes (OcgStandardReal, ...) plus the generic
# enum out-param holder, all defined in OcgPrimitiveWrappers.hpp.  These must be
# registered so GDScript can instantiate them (OcgStandardReal.new() etc.).
_PRIMITIVE_WRAPPER_CLASSES = [
    "OcgStandardReal",
    "OcgStandardInteger",
    "OcgStandardBoolean",
    "OcgStandardShortReal",
    "OcgStandardByte",
    "OcgStandardCharacter",
    "OcgStandardLongInteger",
    "OcgStandardULongInteger",
    "OcgTCollectionAsciiString",
    "OcgTCollectionExtendedString",
    "OcgEnumValue",
]


def generate_module_header(modules: list[ModuleDecl], output_dir: Path,
                           enums_host: bool = False) -> str:
    """Generate module.h content with all includes and registration calls."""
    includes = []
    registrations = []

    if enums_host:
        includes.append('#include "OcgEnums.hpp"')
        registrations.append('    godot::ClassDB::register_class<godot::OcgEnums>();')

    for mod in modules:
        for cls in mod.classes:
            includes.append(f'#include "{cls.wrapper_name}.hpp"')
            registrations.append(f'    godot::ClassDB::register_class<{cls.wrapper_name}>();')

    if _PRIMITIVE_WRAPPER_CLASSES:
        includes.append('#include "OcgPrimitiveWrappers.hpp"')
        for wname in _PRIMITIVE_WRAPPER_CLASSES:
            registrations.append(f'    godot::ClassDB::register_class<{wname}>();')

    content = f"""// AUTOGENERATED by OpenCASCADE.gd-autowrapper — DO NOT EDIT
#ifndef AUTOWRAPPER_MODULE_H
#define AUTOWRAPPER_MODULE_H

#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/godot.hpp>

{chr(10).join(includes)}

inline void gdext_initialize_module_auto(godot::ModuleInitializationLevel p_level) {{
    if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {{
        return;
    }}
{chr(10).join(registrations)}
}}

inline void gdext_uninitialize_module_auto(godot::ModuleInitializationLevel p_level) {{
    (void)p_level;
}}

#endif // AUTOWRAPPER_MODULE_H
"""

    return content
