"""Dynamic type mapping from OCCT types to wrapper/godot-cpp types."""

from __future__ import annotations

from model import ClassDecl, ClassKind, EnumDecl, OCCTType, occt_name_to_wrapper
from classify.skippable import _resolve_handle_inner


# Primitive type mappings (OCCT -> godot-cpp)
PRIMITIVE_MAP = {
    "void": "void",
    "bool": "bool",
    "Standard_Boolean": "bool",
    "char": "char",
    "Standard_Character": "char",
    "unsigned char": "uint8_t",
    "Standard_Byte": "uint8_t",
    "short": "int16_t",
    "unsigned short": "uint16_t",
    "uint16_t": "uint16_t",
    "int": "int32_t",
    "Standard_Integer": "int32_t",
    "unsigned int": "uint32_t",
    "uint32_t": "uint32_t",
    "long": "int64_t",
    "long long": "int64_t",
    "int64_t": "int64_t",
    "unsigned long long": "uint64_t",
    "uint64_t": "uint64_t",
    "float": "float",
    "Standard_ShortReal": "float",
    "double": "double",
    "Standard_Real": "double",
    "long double": "double",
    "Standard_CString": "String",
    "Standard_Size": "uint64_t",
    "Standard_ExtCharacter": "int32_t",
    "Standard_ExtString": "String",
    "Graphic3d_ZLayerId": "int32_t",
    "Graphic3d_ArrayFlags": "int32_t",
}

# Mapping from OCCT primitive type to wrapper class name for non-const ref output params.
# These are lightweight wrapper classes generated by the autowrapper to pass mutable
# references to primitive values across the godot-cpp FFI boundary.
_PRIMITIVE_WRAPPER_MAP = {
    "Standard_Real": "OcgStandardReal",
    "Standard_Integer": "OcgStandardInteger",
    "Standard_Boolean": "OcgStandardBoolean",
    "Standard_ShortReal": "OcgStandardShortReal",
    "Standard_Byte": "OcgStandardByte",
    "Standard_Character": "OcgStandardCharacter",
    "double": "OcgStandardReal",
    "int32_t": "OcgStandardInteger",
    "int": "OcgStandardInteger",
    "bool": "OcgStandardBoolean",
    "float": "OcgStandardShortReal",
    "uint8_t": "OcgStandardByte",
    "char": "OcgStandardCharacter",
    "int64_t": "OcgStandardLongInteger",
    "uint64_t": "OcgStandardULongInteger",
}

# C++ types for primitive wrapper classes
PRIMITIVE_WRAPPER_CPP_TYPE = {
    "OcgStandardReal": "double",
    "OcgStandardInteger": "int32_t",
    "OcgStandardBoolean": "bool",
    "OcgStandardShortReal": "float",
    "OcgStandardByte": "uint8_t",
    "OcgStandardCharacter": "char",
    "OcgStandardLongInteger": "int64_t",
    "OcgStandardULongInteger": "uint64_t",
}

# Collection wrapper types: OCCT typedef'd NCollection instantiations that can't
# be extracted as standalone classes.  Maps OCCT name → (OCCT C++ type, include).
# These are opaque VALUE types wrapped in RefCounted for godot-cpp.
COLLECTION_TYPES: dict[str, tuple[str, str]] = {
    # Lists (NCollection_List<T>)
    "TopTools_ListOfShape":          ("NCollection_List<TopoDS_Shape>",          "<TopTools_ListOfShape.hxx>"),
    "TColStd_ListOfInteger":         ("NCollection_List<Standard_Integer>",      "<TColStd_ListOfInteger.hxx>"),
    "TColStd_ListOfAsciiString":     ("NCollection_List<TCollection_AsciiString>","<TColStd_ListOfAsciiString.hxx>"),
    "TColStd_ListOfReal":            ("NCollection_List<Standard_Real>",         "<TColStd_ListOfReal.hxx>"),
    "TColStd_ListOfTransient":       ("NCollection_List<opencascade::handle<Standard_Transient>>", "<TColStd_ListOfTransient.hxx>"),
    # Sequences (NCollection_Sequence<T>)
    "TDF_LabelSequence":             ("NCollection_Sequence<TDF_Label>",         "<TDF_LabelSequence.hxx>"),
    "TopTools_SequenceOfShape":      ("NCollection_Sequence<TopoDS_Shape>",      "<TopTools_SequenceOfShape.hxx>"),
    "TColStd_SequenceOfHAsciiString":("NCollection_Sequence<opencascade::handle<TCollection_HAsciiString>>", "<TColStd_SequenceOfHAsciiString.hxx>"),
    "TColStd_SequenceOfExtendedString": ("NCollection_Sequence<TCollection_ExtendedString>", "<TColStd_SequenceOfExtendedString.hxx>"),
    "TColStd_SequenceOfHExtendedString":("NCollection_Sequence<opencascade::handle<TCollection_HExtendedString>>", "<TColStd_SequenceOfHExtendedString.hxx>"),
    "TColgp_SequenceOfPnt":          ("NCollection_Sequence<gp_Pnt>",            "<TColgp_SequenceOfPnt.hxx>"),
    # Array1 (NCollection_Array1<T>)
    "TColgp_Array1OfPnt":            ("NCollection_Array1<gp_Pnt>",              "<TColgp_Array1OfPnt.hxx>"),
    "TColgp_Array1OfPnt2d":          ("NCollection_Array1<gp_Pnt2d>",            "<TColgp_Array1OfPnt2d.hxx>"),
    "TColgp_Array1OfVec":            ("NCollection_Array1<gp_Vec>",              "<TColgp_Array1OfVec.hxx>"),
    "TColStd_Array1OfReal":          ("NCollection_Array1<Standard_Real>",       "<TColStd_Array1OfReal.hxx>"),
    "TColStd_Array1OfInteger":       ("NCollection_Array1<Standard_Integer>",    "<TColStd_Array1OfInteger.hxx>"),
    # Array2 (NCollection_Array2<T>)
    "TColgp_Array2OfPnt":            ("NCollection_Array2<gp_Pnt>",              "<TColgp_Array2OfPnt.hxx>"),
    "TColStd_Array2OfReal":          ("NCollection_Array2<Standard_Real>",       "<TColStd_Array2OfReal.hxx>"),
    # DataMaps (NCollection_DataMap<K,V>)
    "TopTools_DataMapOfShapeListOfShape": ("NCollection_DataMap<TopoDS_Shape,TopTools_ListOfShape,TopTools_ShapeMapHasher>", "<TopTools_DataMapOfShapeListOfShape.hxx>"),
    "TopTools_DataMapOfShapeShape":  ("NCollection_DataMap<TopoDS_Shape,TopoDS_Shape,TopTools_ShapeMapHasher>", "<TopTools_DataMapOfShapeShape.hxx>"),
    "TopTools_DataMapOfShapeBox":    ("NCollection_DataMap<TopoDS_Shape,Bnd_Box,TopTools_ShapeMapHasher>", "<TopTools_DataMapOfShapeBox.hxx>"),
    "TColStd_DataMapOfStringInteger":("NCollection_DataMap<TCollection_AsciiString,Standard_Integer,TCollection_AsciiString::StringMapHasher>", "<TColStd_DataMapOfStringInteger.hxx>"),
    "TDataStd_DataMapOfStringString":("NCollection_DataMap<TCollection_AsciiString,TCollection_AsciiString,TCollection_AsciiString::StringMapHasher>", "<TDataStd_DataMapOfStringString.hxx>"),
    "TDataStd_DataMapOfStringReal":  ("NCollection_DataMap<TCollection_AsciiString,Standard_Real,TCollection_AsciiString::StringMapHasher>", "<TDataStd_DataMapOfStringReal.hxx>"),
    "TDataStd_DataMapOfStringByte":  ("NCollection_DataMap<TCollection_AsciiString,Standard_Byte,TCollection_AsciiString::StringMapHasher>", "<TDataStd_DataMapOfStringByte.hxx>"),
    # Maps
    "TopTools_IndexedMapOfShape":     ("NCollection_IndexedMap<TopoDS_Shape,TopTools_ShapeMapHasher>", "<TopTools_IndexedMapOfShape.hxx>"),
    "TopTools_IndexedDataMapOfShapeReal": ("NCollection_IndexedDataMap<TopoDS_Shape,Standard_Real,TopTools_ShapeMapHasher>", "<TopTools_IndexedDataMapOfShapeReal.hxx>"),
    "TopTools_MapOfShape":           ("NCollection_Map<TopoDS_Shape,TopTools_ShapeMapHasher>", "<TopTools_MapOfShape.hxx>"),
    "TDF_LabelMap":                  ("NCollection_Map<TDF_Label>",              "<TDF_LabelMap.hxx>"),
    "TDF_LabelIndexedMap":           ("NCollection_IndexedMap<TDF_Label>",       "<TDF_LabelIndexedMap.hxx>"),
    "IMeshData::MapOfInteger":       ("NCollection_Map<int>",                    "<IMeshData_MapOfInteger.hxx>"),
    # TDF sequences/lists/arrays
    "TDF_DeltaList":                 ("NCollection_Sequence<opencascade::handle<TDF_Delta>>", "<TDF_DeltaList.hxx>"),
    "TDF_AttributeArray1":           ("NCollection_Array1<opencascade::handle<TDF_Attribute>>", "<TDF_AttributeArray1.hxx>"),
    "TDF_AttributeDeltaList":        ("NCollection_Sequence<opencascade::handle<TDF_AttributeDelta>>", "<TDF_AttributeDeltaList.hxx>"),
    "TDF_LabelList":                 ("NCollection_Sequence<TDF_Label>",         "<TDF_LabelList.hxx>"),
}


class TypeMap:
    """Builds and queries the type mapping for a set of classified classes."""

    def __init__(self, classes: list[ClassDecl], enums: list[EnumDecl] | None = None):
        self._wrapper_names: dict[str, str] = {}  # OCCT name -> wrapper name
        self._classes: dict[str, ClassDecl] = {}  # OCCT name -> ClassDecl
        self._enum_names: set[str] = set()        # known enum type names
        self._build(classes, enums or [])

    def _build(self, classes: list[ClassDecl], enums: list[EnumDecl]):
        for cls in classes:
            self._classes[cls.name] = cls
            self._wrapper_names[cls.name] = cls.wrapper_name
            # Collect nested enum full names (e.g. "gp_Dir::D")
            for ne in cls.nested_enums:
                self._enum_names.add(f"{cls.name}::{ne.name}")
        # Collect standalone enum names
        for e in enums:
            self._enum_names.add(e.name)
        # Register collection wrapper types
        for occt_name in COLLECTION_TYPES:
            wname = occt_name_to_wrapper(occt_name, "")
            self._wrapper_names[occt_name] = wname

    def wrapper_name(self, occt_name: str) -> str | None:
        """Get the wrapper name for an OCCT type, or None if not wrapped."""
        return self._wrapper_names.get(occt_name)

    def class_kind(self, occt_name: str) -> ClassKind | None:
        """Get the ClassKind for a wrapped OCCT type, or None."""
        cls = self._classes.get(occt_name)
        return cls.kind if cls else None

    def is_wrapped(self, occt_name: str) -> bool:
        return occt_name in self._wrapper_names

    def cpp_type_for_param(self, otype: OCCTType) -> str:
        """Get the C++ parameter type for the wrapper method signature."""
        base = otype.base_name

        # Non-const ref output params of primitives → Ref<OcgPrimitiveWrapper>
        if otype.is_ref and not otype.is_const and not otype.is_handle:
            if base in PRIMITIVE_MAP and base != "void":
                wname = _PRIMITIVE_WRAPPER_MAP.get(base)
                if wname:
                    return f"Ref<{wname}>"
            # Non-const ref of wrapped class → Ref<Wrapper>
            wname = self._wrapper_names.get(base)
            if wname:
                return f"Ref<{wname}>"
            # Non-const ref of enum → int32_t (mutable ref param)
            if self._is_enum(base):
                return "int32_t"

        # const char* / char* params → String (godot string → OCCT)
        if base in ("char", "Standard_CString") and otype.is_pointer:
            return "String"

        # char param (not pointer) → int32_t (godot-cpp doesn't support char)
        if base in ("char", "Standard_Character") and not otype.is_pointer:
            return "int32_t"

        # Primitives
        if base in PRIMITIVE_MAP:
            return PRIMITIVE_MAP[base]

        # Enum types (nested or standalone) → int32_t
        if self._is_enum(base):
            return "int32_t"

        # Handle types -> Ref<T>
        if otype.is_handle:
            inner = _resolve_handle_inner(otype.handle_inner)
            wname = self._wrapper_names.get(inner, inner)
            return f"Ref<{wname}>"

        # Wrappable types with wrappers -> Ref<T> for godot-cpp PtrToArg
        wname = self._wrapper_names.get(base)
        if wname:
            return f"Ref<{wname}>"

        # Unwrapped OCCT types: pass through as-is
        if otype.is_const and otype.is_ref:
            return f"const {base}&"
        if otype.is_ref:
            return f"{base}&"
        return base

    def cpp_type_for_return(self, otype: OCCTType | None) -> str:
        """Get the C++ return type for the wrapper method.

        Value type returns always become Ref<T> (the method wraps in a new object).
        Reference returns to value types also become Ref<T> (copy into wrapper).
        """
        if otype is None or otype.is_void:
            return "void"

        base = otype.base_name

        # const char* / char* returns → String
        if base in ("char", "Standard_CString") and otype.is_pointer:
            return "String"

        # char (non-pointer) return → int32_t (godot-cpp doesn't support char)
        if base in ("char", "Standard_Character") and not otype.is_pointer:
            return "int32_t"

        if base in PRIMITIVE_MAP:
            return PRIMITIVE_MAP[base]

        # Enum types (nested or standalone) → int32_t
        if self._is_enum(base):
            return "int32_t"

        if otype.is_handle:
            inner = _resolve_handle_inner(otype.handle_inner)
            wname = self._wrapper_names.get(inner, inner)
            return "Ref<{}>".format(wname)

        wname = self._wrapper_names.get(base)
        if wname:
            # All wrapped type returns become Ref<T> (value types wrapped in new object)
            if self.is_value_type(base):
                return "Ref<{}>".format(wname)
            # Non-value wrapped types (handles, etc.)
            if otype.is_ref and otype.is_const:
                return "const {}&".format(wname)
            if otype.is_ref:
                return "{}&".format(wname)
            return wname

        # Unwrapped types: pass through
        if otype.is_ref and otype.is_const:
            return "const {}&".format(base)
        if otype.is_ref:
            return "{}&".format(base)
        return base

    def gd_type_for_param(self, otype: OCCTType) -> str:
        """Get the GDScript-facing parameter type (for D_METHOD)."""
        base = otype.base_name

        # Primitive wrapper types as params → the wrapper class name
        if base in _PRIMITIVE_WRAPPER_MAP and (otype.is_ref and not otype.is_const):
            return _PRIMITIVE_WRAPPER_MAP[base]

        # char (non-pointer) → int (godot-cpp doesn't support char)
        if base in ("char", "Standard_Character") and not otype.is_pointer:
            return "int"

        if base in PRIMITIVE_MAP:
            gtype = PRIMITIVE_MAP[base]
            if gtype in ("int32_t", "int64_t", "uint32_t", "uint64_t", "int16_t", "uint16_t"):
                return "int"
            if gtype in ("float", "double"):
                return "float"
            if gtype == "bool":
                return "bool"
            if gtype == "String":
                return "String"
            return gtype

        # Enum types → int
        if self._is_enum(base):
            return "int"

        if otype.is_handle:
            inner = _resolve_handle_inner(otype.handle_inner)
            wname = self._wrapper_names.get(inner, inner)
            return wname

        wname = self._wrapper_names.get(base)
        if wname:
            return wname

        return base

    def gd_type_for_return(self, otype: OCCTType | None) -> str:
        """Get the GDScript-facing return type."""
        if otype is None or otype.is_void:
            return "void"
        # char returns → int (godot-cpp doesn't support char)
        if otype.base_name in ("char", "Standard_Character") and not otype.is_pointer:
            return "int"
        # Primitive wrapper returns → the wrapper class name
        if otype.base_name in _PRIMITIVE_WRAPPER_MAP:
            return _PRIMITIVE_WRAPPER_MAP[otype.base_name]
        return self.gd_type_for_param(otype)

    def is_value_type(self, occt_name: str) -> bool:
        """Check if an OCCT type is a value type (stored inline, not by handle).

        All non-REF_COUNTED wrapped types (VALUE, TOPODS_SHAPE, BUILDER, OTHER)
        store native data and need Ref<T> wrapping for godot-cpp.
        Collection types are always value types.
        """
        if occt_name in COLLECTION_TYPES:
            return True
        cls = self._classes.get(occt_name)
        if cls:
            return cls.kind != ClassKind.REF_COUNTED
        # Default: if it's a primitive, it's a value
        return occt_name in PRIMITIVE_MAP

    def is_refcounted(self, occt_name: str) -> bool:
        """Check if an OCCT type is REF_COUNTED (uses _handle, not _native)."""
        cls = self._classes.get(occt_name)
        if cls:
            return cls.kind == ClassKind.REF_COUNTED
        return False

    def _is_enum(self, base_name: str) -> bool:
        """Check if a type name is an enum."""
        return base_name in self._enum_names
